FROM python:3.11-slim-bullseye

RUN apt-get update \
&& apt-get install gcc -y \
&& apt-get clean

COPY requirements.txt /tmp/

RUN python -m pip install --upgrade pip

RUN pip install -r /tmp/requirements.txt

WORKDIR /redis-pubsub

COPY . /redis-pubsub

RUN pip install -e /redis-pubsub/src

CMD python src/allocation/entrypoints/redis_eventconsumer.py

#EXPOSE 8001

#CMD uvicorn --host 0.0.0.0 --port 8000 src.allocation.entrypoints.fast_api:app --workers 1 --log-level debug --forwarded-allow-ips="*" --proxy-headers