version: "3.8"

services:

  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DATABASE_URI=postgresql://user:password@postgres:5432/allocation
      - API_HOST=api
      - PYTHONPATH=/app
    volumes:
      - ./src:/app/src
      - ./tests:/tests
    ports:
      - "8001:8000"

  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"